<?php
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3529, 0, 'pp_top_right_content', 'Follow us @ipeerapong | Call now +66 867055180', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3532, 0, 'pp_font', 'DroidItalic_Serif_italic_400.font', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3533, 0, 'pp_body_font', 'Helvatica,Arial,sans-serif', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3534, 0, 'pp_body_font_size', '12', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3535, 0, 'pp_tagline_font_size', '18', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3536, 0, 'pp_footer_header_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3537, 0, 'pp_sidebar_header_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3538, 0, 'pp_post_title_font_size', '20', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3539, 0, 'pp_caption_margintop_size', '0', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3540, 0, 'pp_h1_size', '28', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3541, 0, 'pp_h2_size', '26', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3542, 0, 'pp_h3_size', '24', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3543, 0, 'pp_h4_size', '20', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3544, 0, 'pp_h5_size', '18', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3545, 0, 'pp_h6_size', '16', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3546, 0, 'pp_bg_pattern', 'jeans', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3547, 0, 'pp_header_bg', '#333a3d', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3548, 0, 'pp_menu_color', '#7f7f7f', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3549, 0, 'pp_font_color', '#444444', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3550, 0, 'pp_link_color', '#495357', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3551, 0, 'pp_hover_link_color', '#0e1e22', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3552, 0, 'pp_h1_font_color', '#555555', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3553, 0, 'pp_button_bg_color', '#ebebeb', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3554, 0, 'pp_button_font_color', '#888888', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3555, 0, 'pp_button_border_color', '#ebebeb', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3556, 0, 'pp_slider_effect', 'jQuery', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3558, 0, 'pp_slider_sort', 'DESC', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3559, 0, 'pp_slider_items', '6', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3560, 0, 'pp_slider_timer', '5', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3561, 0, 'pp_segments', '9', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3562, 0, 'pp_tween_time', '1', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3563, 0, 'pp_tween_delay', '100', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3564, 0, 'pp_tween_type', 'easeInOutExpo', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3565, 0, 'pp_z_distance', '700', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3567, 0, 'pp_homepage_tagline', 'The greatest danger for most of us is not that we aim too high and we miss it,  but we aim too low and reach it. - Michelangelo', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3568, 0, 'pp_portfolio_style', 'f', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3569, 0, 'pp_portfolio_sort', 'DESC', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3570, 0, 'pp_portfolio_sorting', 'swing', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3571, 0, 'pp_portfolio_display_set', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3572, 0, 'pp_portfolio_display_desc', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3573, 0, 'pp_gallery_style', '4', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3574, 0, 'pp_gallery_sort', 'DESC', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3576, 0, 'pp_blog_title', 'Blog', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3577, 0, 'pp_blog_display_author', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3578, 0, 'pp_blog_display_related', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES (3387, 0, 'pp_blog_meta', 's:66:\"a:5:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";i:3;s:1:\"4\";i:4;s:1:\"5\";}\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3581, 0, 'pp_contact_thankyou', 'Thank you! We will get back to you as soon as possible', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES (3390, 0, 'pp_contact_form', 's:42:\"a:3:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";}\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3583, 0, 'pp_footer_display_sidebar', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3584, 0, 'pp_footer_style', '4', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3585, 0, 'pp_footer_text', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES(3586, 0, 'pp_seo_enable', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES (3399, 0, 'pp_blog_meta_sort_data', 's:66:\"a:5:{i:0;s:1:\"4\";i:1;s:1:\"5\";i:2;s:1:\"2\";i:3;s:1:\"1\";i:4;s:1:\"3\";}\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `wp_options` VALUES (3400, 0, 'pp_contact_form_sort_data', 's:42:\"a:3:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";}\";', 'yes');");
?>